python test-1-cesar.py
python test-2-vigenere-cipher.py
python test-3-freq-IC.py
python test-4-decalages.py
python test-5-cryptanalyse-V1.py
python test-6-ICM-decalages.py
python test-7-cryptanalyse-V2.py
python test-8-correlations.py
python test-9-cryptanalyse-V3.py
